service: mcq-maker
frameworkVersion: "3"

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 128
  region: ap-south-1
  stage: ${opt:stage, 'dev'}
  httpApi:
    cors: false

functions:
  mcqMaker:
    handler: server.handler
    events:
      - httpApi: ANY /
      - httpApi: "ANY /{proxy+}"
